### ISSUE TITLE
Control arm using mujoco_ros_control

### ISSUE THREAD

**Issue by Daviesss** [ubi-agni/mujoco_ros_pkgs#34]
I have been able to get some topics up from mujoco to ros , my question is how do i control robot arm using the mujoco_ros_control package . I will be glad if i get a direction .

**Comment by DavidPL1** [comment]
You can take a look at https://github.com/ubi-agni/franka_ros_mujoco as an example.

There are 3 things you have to consider:
1. you have to load a URDF into ROS
2. the joint names you want to control must be consistent in the mujoco model and URDF
3. you have to load the control plugin and define which hardware interface to load

To 3: this would be this part:
https://github.com/ubi-agni/franka_ros_mujoco/blob/852a184310ab2a04a0286d5d348f585a5b7b2983/config/default_mjplugin_config.yaml#L1-L5

However, the panda robot uses a custom hardware interface, normally the default interface suffices. In that case instead use:

```yaml
MujocoPlugins:
  - type: mujoco_ros_control/MujocoRosControlPlugin
    hardware:
      type: mujoco_ros_control/DefaultRobotHWSim
      control_period: 0.001
```
