### ISSUE TITLE
Setting Initial Positions doesnt work?

### ISSUE THREAD

**Issue by uahic** [ubi-agni/mujoco_ros_pkgs#42]
Hi there,

I had a look at the fork of   @tenfoldpaper and added the missing implementation (so far locally) to read out initial positions from the rosparam yaml. 

The joint values are also set properly. When unpausing the simulation, the arm suddenly moves rapidly back into the 0-Pose , even if I do not compile the mujoco_ros2_control subpackages (adding colcon ignore files) to hopefully make sure no controller are enforcing this behavior.  The arm is also not folding back in this position due to gravity (that would look very different), it really unwinds towards the 0 pose

So I am not really sure what is going on here and would like to ask if you know if that happened in the ROS1 version as well?

Thank you! :) 

Here my current fork (also had to do some dirty hacking in Cmake to get it even compiling)
https://github.com/uahic/mujoco_ros_pkgs/tree/wip_humble_buildable

Jump to relevant lines for reading init joint positions:
https://github.com/uahic/mujoco_ros_pkgs/blob/49510c11fd02e7096e100ab4679f1782014e93a0/mujoco_ros/src/ros_two/parameter_interface.cpp#L120

![Image](https://github.com/user-attachments/assets/8de3eed4-6db9-49b0-9f30-da4c65363756)

![Image](https://github.com/user-attachments/assets/c7d43f9a-a93a-4346-b502-e6c0119e2618)

**Comment by DavidPL1** [comment]
By just looking at the code it looks fine to me. Do you, by any chance, have actuators defined in the used modelfile?

Joint angles are set through qpos and control applies torque directly at the joints, which can interfere with an actuator control signal. The default control signal forcing the joints to it's zero configuration could explain what you are experiencing here.

If you have no actuators defined I'll have to dig deeper into the issue in the next few days.

**Comment by uahic** [comment]
@DavidPL1 Hi David,

yes indeed. It looks roughly like this (the ur10e.xml file, copied from deepminds mujoco_mangenerie) is glued together with other files to make up the entire scene in a python script that is run in the launch file prior to starting mujoco, joint names are then prefixed by "ur_"):

```

  <actuator>
    <general class="size4" name="shoulder_pan_joint_act_pos" joint="shoulder_pan_joint"/>
    <general class="size4" name="shoulder_lift_joint_act_pos" joint="shoulder_lift_joint"/>
    <general class="size3_limited" name="elbow_joint_act_pos" joint="elbow_joint"/>
    <general class="size2" name="wrist_1_joint_act_pos" joint="wrist_1_joint"/>
    <general class="size2" name="wrist_2_joint_act_pos" joint="wrist_2_joint"/>
    <general class="size2" name="wrist_3_joint_act_pos" joint="wrist_3_joint"/>

    <!-- <position class="size4" name="shoulder_pan_joint_act_pos" joint="ur_shoulder_pan_joint"/>
    <position class="size4" name="shoulder_lift_joint_act_pos" joint="ur_shoulder_lift_joint"/>
    <position class="size3_limited" name="elbow_joint_act_pos" joint="ur_elbow_joint"/>
    <position class="size2" name="wrist_1_joint_act_pos" joint="ur_wrist_1_joint"/>
    <position class="size2" name="wrist_2_joint_act_pos" joint="ur_wrist_2_joint"/>
    <position class="size2" name="wrist_3_joint_act_pos" joint="ur_wrist_3_joint"/> -->
  </actuator>

```

and in URDF


```
    <ros2_control name="MujocoRos2System" type="system">
        <hardware>
            <plugin>mujoco_ros2_control_system/MujocoRos2System</plugin>
        </hardware>

        <xacro:joint_interface name="ur_shoulder_pan_joint" p="1" i="1" d="3" initial_pos="-1.5708"/>
        <xacro:joint_interface name="ur_shoulder_lift_joint" p="1" i="1" d="3" initial_pos="-1.2217"/>
        <xacro:joint_interface name="ur_elbow_joint" p="5" i="1" d="1" initial_pos="-2.0944"/>
        <xacro:joint_interface name="ur_wrist_1_joint" p="1" i="1" d="1" initial_pos="-1.3963"/>
        <xacro:joint_interface name="ur_wrist_2_joint" p="5" i="0.5" d="5" initial_pos="1.5708"/>
        <xacro:joint_interface name="ur_wrist_3_joint" p="1" i="0.1" d="1" initial_pos="0.0"/>
     </ros2_control>

```


whereas  (Tried initial_value as it worked before in mujoco_ros2_control package and   initial_position like in tenfolds panda package when using ros_mujoco_pkgs)

```
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

        <!-- Individual joint. -->
        <xacro:macro name="joint_interface" params="name p i d initial_pos">
                <joint name="${name}">
                        <param name="p">${p}</param>
                        <param name="i">${i}</param>
                        <param name="d">${d}</param>
                        <param name="initial_position">${initial_pos}</param>
                        <command_interface name="position"/>
                        <!-- <command_interface name="velocity"/>
                        <command_interface name="effort"/> -->
                        <state_interface name="position">
                                <param name="initial_value">${initial_pos}</param>
                        </state_interface>
                        <state_interface name="velocity"/>
                        <state_interface name="effort"/>
                </joint>
        </xacro:macro>

</robot>

```

The setup worked before in mujoco_ros2_control (the competitor package) quite well as it is. Basically I just added the necessary config files and suffixed the actuators with  '_acc_pos' (which is not so nice as you have to rename 3rd party description packages in turn, potentially :/ )

**Comment by uahic** [comment]
Addition: it seems also to move even if actuators and joints in URDF are commented out.

**Comment by DavidPL1** [comment]
I suppose the other package uses the MuJoCo actuator to apply the control whereas this package doesn't and applies the torque computed by ROS control directly at the joints. I've already thought about either adapting to the same behavior or deactivating actuators programmaticaly to avoid these compatibility issues. For now, commenting the actuators in the MuJoCo XML should fix your issue.
In fact, defining ROS actuators and MuJoCo actuators is somewhat redundant and is prone to errors in case of inconsistent configuration. 

Edit:
> suffixed the actuators with '_acc_pos' (which is not so nice as you have to rename 3rd party description packages in turn, potentially :/ )

Not really sure what you mean by this. Actuator names are irrelevant in this package. Actuators in MuJoCo do the same thing as ROS control: given a target value for a joint, a force/torque is computed based on the actuator properties and the force/torque is applied at the joint. In this package what happens when you define both ROS and MuJoCo actuators is that both act on the joints they control individually, most probably causing the joints to jerk around because of the interference. 

> Addition: it seems also to move even if actuators and joints in URDF are commented out.

If you disabled the ROS control plugin beforehand the URDF isn't used anyway, so this is expected behavior.

I've just created #43, on completion of it your setup should work out of the box.
In the meantime, you need to remove the actuator definitions in your `ur10e.xml` copy

**Comment by uahic** [comment]
@DavidPL1 Thank you first of all for the instant support :) 

I somehow assumed the implementation seeks for actuators in Mujoco and forwards the output of the ROS controllers as their input values. Ok in this case, my assumption was just wrong.

Will check it out in the evening, thanks!

**Comment by tenfoldpaper** [comment]
I haven't really looked into how the other package does it, but the way it is done in my implementation is, any mention of mujoco/real hardware is abstracted away at the controller implementation level, so as to enable developing controllers that work on both setups, which is a sorely needed feature in my lab.

I could look into setting up some additional rosparams where you can define which actuators should be deactivated. 
The way I set up the initial pos in my multipanda_ros2 code is a leftover pattern from when I tried developing a built-in mujoco sim directly into the HardwareInterface, before I discovered @DavidPL1 's work. Though, I would argue that all ros2-control joint-relevant information should be contained inside the corresponding ros2_control.xacro file, and we could perhaps set it up so that the values defined in the xacro file overrides the initial values set up inside the mujoco_ros simulator itself, to keep things a bit cleaner.

Renaming external MuJoCo xml files is a pain in the neck, I agree, but as long as MuJoCo doesn't support variable-like functionalities, that is an evil we have to deal with :/ Otherwise, there is no good way to look for actuators in MuJoCo that correspond to the ones defined in the URDF (as far as I know). At least, it's something that you have to do just once in the beginning and forget about it.

**Comment by uahic** [comment]
@DavidPL1  @tenfoldpaper I just pulled  @DavidPL1 's  pr-history branch and copy&pasted my previous code snipped to read out initial_joints again, now this works, but the arm sinks slowly down (not anymore into 0-position but it just folds due to gravity), the controllers are clearly not acting on the joint eventhough they have been loaded. 

@DavidPL1 
I am a bit confused now because I have removed all actuators in the XML files but now it seems no interfaces are found by ROS control (the interfaces are still declared in xacro/urdf). Is a <motor> tag required for each joint among the XML actuators as sort of a transmission mechanism? 

this is how my config for ros2_control looks like:

```
mujoco_server:
  ros__parameters:
    MujocoPlugins:
      names:
      - mujoco_ros2_control
      mujoco_ros2_control:
        type: mujoco_ros2_control::MujocoRos2ControlPlugin
        hardware:
          type: mujoco_ros_control/RobotHW
          control_period: 0.001
        params:
          namespace: ""
          robot_description_node: "robot_state_publisher"
          robot_description: "robot_description"

controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: position_controllers/GripperActionController

joint_trajectory_controller:
  ros__parameters:
    interface_name: position
    joints:
    - ur_shoulder_pan_joint
    - ur_shoulder_lift_joint
    - ur_elbow_joint
    - ur_wrist_1_joint
    - ur_wrist_2_joint
    - ur_wrist_3_joint
    command_interfaces:
    - position
    state_interfaces:
    - position
    - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ur_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

gripper_controller:
  ros__parameters:
    joint: ur_robotiq_finger_joint
    joints:
    - ur_robotiq_finger_joint
    max_effort: 4.0
    # max_effort_interface: ur_robotiq_finger_joint/max_effort_interface
    max_velocity: 0.1
    goal_tolerance: 0.05
    stall_timeout: 1.0
    allow_stalling: true
    stall_velocity_threshold: 0.001
    interface_name: position
    command_interfaces:
    - position
    state_interfaces:
    - position
    - effort
    - velocity

```

The error:

```
[mujoco_node-1] [ERROR] [1746708214.292616997] [resource_manager] [prepare_command_mode_switch]: Not acceptable command interfaces combination: 
[mujoco_node-1] Start interfaces: 
[mujoco_node-1] [
[mujoco_node-1]   ur_shoulder_pan_joint/position
[mujoco_node-1]   ur_shoulder_lift_joint/position
[mujoco_node-1]   ur_elbow_joint/position
[mujoco_node-1]   ur_wrist_1_joint/position
[mujoco_node-1]   ur_wrist_2_joint/position
[mujoco_node-1]   ur_wrist_3_joint/position
[mujoco_node-1] ]
[mujoco_node-1] Stop interfaces: 
[mujoco_node-1] [
[mujoco_node-1] ]
[mujoco_node-1] Not existing: 
[mujoco_node-1] [
[mujoco_node-1]  ur_shoulder_pan_joint/position
[mujoco_node-1]  ur_shoulder_lift_joint/position
[mujoco_node-1]  ur_elbow_joint/position
[mujoco_node-1]  ur_wrist_1_joint/position
[mujoco_node-1]  ur_wrist_2_joint/position
[mujoco_node-1]  ur_wrist_3_joint/position
[mujoco_node-1] ]
[mujoco_node-1] 
[mujoco_node-1] [ERROR] [1746708214.292638433] [controller_manager] [switch_controller]: Could not switch controllers since prepare command mode switch was rejected.
[spawner-3] [ERROR] [1746708214.293311112] [spawner_joint_state_broadcaster] [main]: Failed to activate controller : joint_trajectory_controller
[ERROR] [spawner-3]: process has died [pid 143021, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner joint_state_broadcaster gripper_controller joint_trajectory_controller --controller-manager /controller_manager --ros-args'].
```
